// This component is no longer used on the Analytics page
// and has been replaced by the TurkeyTurnoverMapCard.
// The component is kept for the Store Detail Page but could be refactored or removed later.
import React, { useMemo, useState } from 'react';
import { useData } from '../DataContext';
import { Comment, WordCloudWord } from '../types';

// Dictionary for common retail/feedback words
const TR_TO_EN_DICT: Record<string, string> = {
    'personel': 'staff',
    'hizmet': 'service',
    'fiyat': 'price',
    'ürün': 'product',
    'ürünler': 'products',
    'temiz': 'clean',
    'temizlik': 'cleanliness',
    'mağaza': 'store',
    'kalite': 'quality',
    'kasa': 'register',
    'sıra': 'queue',
    'güler': 'smiling',
    'yüzlü': 'faced',
    'yardımcı': 'helpful',
    'teşekkür': 'thanks',
    'memnun': 'satisfied',
    'kötü': 'bad',
    'iyi': 'good',
    'güzel': 'nice',
    'harika': 'great',
    'mükemmel': 'excellent',
    'berbat': 'terrible',
    'pahalı': 'expensive',
    'ucuz': 'cheap',
    'indirim': 'discount',
    'kampanya': 'campaign',
    'çeşit': 'variety',
    'beden': 'size',
    'renk': 'color',
    'kumaş': 'fabric',
    'kasiyer': 'cashier',
    'müdür': 'manager',
    'çalışan': 'employee',
    'çalışanlar': 'employees',
    'ilgi': 'attention',
    'alaka': 'relevance',
    'saygısız': 'disrespectful',
    'kibar': 'polite',
    'yavaş': 'slow',
    'hızlı': 'fast',
    'kalabalık': 'crowded',
    'boş': 'empty',
    'düzenli': 'organized',
    'dağınık': 'messy',
    'pis': 'dirty',
    'havasız': 'stuffy',
    'sıcak': 'hot',
    'soğuk': 'cold',
    'müzik': 'music',
    'ses': 'sound',
    'ışık': 'light',
    'karanlık': 'dark',
    'güler yüzlü': 'smiling',
    'yardımcı oldular': 'helpful',
    'ilgilendiler': 'cared',
    'çok': 'very',
    'biraz': 'a bit',
    'fazla': 'too much',
    'yetersiz': 'insufficient',
    'yeterli': 'sufficient',
    'bekledik': 'waited',
    'bekleme': 'waiting',
    'bulamadım': 'could not find',
    'yoktu': 'was not there',
    'vardı': 'was there',
    'görevli': 'attendant',
    'müşteri': 'customer',
    'memnuniyet': 'satisfaction',
    'şikayet': 'complaint',
    'öneri': 'suggestion',
    'kaba': 'rude',
    'saygılı': 'respectful',
    'ilgili': 'attentive',
    'ilgisiz': 'inattentive',
    'güleryüz': 'smiling face',
    'suratsız': 'sullen',
    'yardımsever': 'helpful',
    'deneme': 'fitting',
    'kabini': 'room',
    'kabin': 'cabin',
    'reyon': 'aisle',
    'raf': 'shelf',
    'düzen': 'order',
    'tertip': 'neatness',
    'ferah': 'spacious',
    'dar': 'narrow',
    'geniş': 'wide',
    'aydınlık': 'bright',
    'koku': 'smell',
    'havalandırma': 'ventilation',
    'klima': 'ac',
    'çalışmıyor': 'not working',
    'bozuk': 'broken',
    'eski': 'old',
    'yeni': 'new',
    'moda': 'fashion',
    'tarz': 'style',
    'model': 'model',
    'seçenek': 'option',
    'alternatif': 'alternative',
    'stok': 'stock',
    'tükendi': 'sold out',
    'kalmadı': 'out of stock',
    'geldi': 'arrived',
    'gelecek': 'will arrive',
    'iade': 'return',
    'değişim': 'exchange',
    'fiş': 'receipt',
    'fatura': 'invoice',
    'kredi': 'credit',
    'kartı': 'card',
    'nakit': 'cash',
    'ödeme': 'payment',
    'sistem': 'system',
    'yavaşlık': 'slowness',
    'hız': 'speed',
    'pratik': 'practical',
    'çözüm': 'solution',
    'odaklı': 'oriented',
    'sorun': 'problem',
    'problem': 'problem',
    'sıkıntı': 'trouble',
    'hata': 'error',
    'yanlış': 'wrong',
    'doğru': 'right',
    'eksik': 'missing',
    'fazla': 'extra',
    'tam': 'complete',
    'yarım': 'half',
    'tavsiye': 'recommend',
    'ederim': 'I do',
    'etmem': 'I do not',
    'kesinlikle': 'absolutely',
    'asla': 'never',
    'her': 'every',
    'zaman': 'time',
    'bazen': 'sometimes',
    'hiç': 'never',
    'sürekli': 'constantly',
    'devamlı': 'continuously',
    'arada': 'occasionally',
    'sırada': 'in line',
    'hemen': 'immediately',
    'şimdi': 'now',
    'sonra': 'later',
    'önce': 'before',
    'bugün': 'today',
    'dün': 'yesterday',
    'yarın': 'tomorrow',
    'sabah': 'morning',
    'öğle': 'noon',
    'akşam': 'evening',
    'gece': 'night',
    'hafta': 'week',
    'sonu': 'end',
    'içi': 'inside',
    'dışı': 'outside',
    'yakın': 'near',
    'uzak': 'far',
    'merkez': 'center',
    'şube': 'branch',
    'mağazası': 'store',
    'çalışanı': 'employee',
    'müdürü': 'manager',
    'kasiyeri': 'cashier',
    'görevlisi': 'attendant',
    'müşterisi': 'customer',
    'ürünü': 'product',
    'fiyatı': 'price',
    'kalitesi': 'quality',
    'hizmeti': 'service',
    'temizliği': 'cleanliness',
    'düzeni': 'order',
    'havası': 'air',
    'kokusu': 'smell',
    'müziği': 'music',
    'ışığı': 'light',
    'sırası': 'queue',
    'kabini': 'cabin',
    'reyonu': 'aisle',
    'rafı': 'shelf',
    'stoku': 'stock',
    'çeşidi': 'variety',
    'bedeni': 'size',
    'rengi': 'color',
    'kumaşı': 'fabric',
    'tarzı': 'style',
    'modeli': 'model',
    'seçeneği': 'option',
    'indirimi': 'discount',
    'kampanyası': 'campaign',
    'iadesi': 'return',
    'değişimi': 'exchange',
    'ödemesi': 'payment',
    'sistemi': 'system',
    'çözümü': 'solution',
    'sorunu': 'problem',
    'hatası': 'error',
    'yanlışı': 'wrong',
    'eksiği': 'missing',
    'fazlası': 'extra',
    'tavsiyesi': 'recommendation',
    'memnuniyeti': 'satisfaction',
    'şikayeti': 'complaint',
    'önerisi': 'suggestion',
    'ilgisi': 'attention',
    'alakası': 'relevance',
    'saygısı': 'respect',
    'kibarlığı': 'politeness',
    'yavaşlığı': 'slowness',
    'hızı': 'speed',
    'kalabalığı': 'crowd',
    'boşluğu': 'emptiness',
    'dağınıklığı': 'messiness',
    'pisliği': 'dirtiness',
    'havasızlığı': 'stuffiness',
    'sıcaklığı': 'heat',
    'soğukluğu': 'coldness',
    'karanlığı': 'darkness',
    'aydınlığı': 'brightness',
    'ferahlığı': 'spaciousness',
    'darlığı': 'narrowness',
    'genişliği': 'width',
    'eskiligi': 'oldness',
    'yeniliği': 'newness',
    'pratikliği': 'practicality',
    'doğruluğu': 'correctness',
    'tamlığı': 'completeness',
    'yarım': 'half',
    'kesinliği': 'certainty',
    'asla': 'never',
    'her': 'every',
    'zamanı': 'time',
    'bazeni': 'sometimes',
    'hiçi': 'nothing',
    'sürekliliği': 'continuity',
    'devamlılığı': 'continuity',
    'aralığı': 'interval',
    'sırası': 'turn',
    'hemenliği': 'immediacy',
    'şimdisi': 'now',
    'sonrası': 'after',
    'öncesi': 'before',
    'bugünü': 'today',
    'dünü': 'yesterday',
    'yarını': 'tomorrow',
    'sabahı': 'morning',
    'öğlesi': 'noon',
    'akşamı': 'evening',
    'gecesi': 'night',
    'haftası': 'week',
    'sonu': 'end',
    'içi': 'inside',
    'dışı': 'outside',
    'yakını': 'near',
    'uzağı': 'far',
    'merkezi': 'center',
    'şubesi': 'branch',
    'kıyafet': 'clothes',
    'giyim': 'clothing',
    'ayakkabı': 'shoes',
    'çanta': 'bag',
    'aksesuar': 'accessory',
    'kasa': 'cash register',
    'kuyruk': 'queue',
    'beklemek': 'waiting',
    'bulmak': 'finding',
    'almak': 'buying',
    'vermek': 'giving',
    'görmek': 'seeing',
    'sormak': 'asking',
    'cevap': 'answer',
    'soru': 'question',
    'yardım': 'help',
    'destek': 'support',
    'ilgisizlik': 'indifference',
    'saygısızlık': 'disrespect',
    'kibarlık': 'politeness',
    'güleryüzlülük': 'friendliness',
    'memnuniyetsizlik': 'dissatisfaction',
    'şikayetçi': 'complaining',
    'tavsiye': 'advice',
    'öneri': 'suggestion',
    'harika': 'wonderful',
    'mükemmel': 'perfect',
    'berbat': 'awful',
    'kötü': 'poor',
    'iyi': 'fine',
    'güzel': 'beautiful',
    'çirkin': 'ugly',
    'pahalı': 'costly',
    'ucuz': 'inexpensive',
    'uygun': 'affordable',
    'indirimli': 'discounted',
    'kampanyalı': 'promotional',
    'çeşitli': 'various',
    'farklı': 'different',
    'aynı': 'same',
    'benzer': 'similar',
    'yeni': 'fresh',
    'eski': 'outdated',
    'temiz': 'tidy',
    'pis': 'filthy',
    'düzenli': 'neat',
    'dağınık': 'cluttered',
    'ferah': 'airy',
    'havasız': 'stifling',
    'sıcak': 'warm',
    'soğuk': 'chilly',
    'karanlık': 'dim',
    'aydınlık': 'well-lit',
    'sesli': 'noisy',
    'sessiz': 'quiet',
    'hızlı': 'quick',
    'yavaş': 'sluggish',
    'pratik': 'handy',
    'zor': 'difficult',
    'kolay': 'easy',
    'doğru': 'accurate',
    'yanlış': 'incorrect',
    'eksik': 'lacking',
    'fazla': 'excessive',
    'tam': 'whole',
    'yarım': 'partial',
    'kesin': 'certain',
    'belki': 'maybe',
    'hiç': 'none',
    'hep': 'always',
    'sürekli': 'continual',
    'devamlı': 'constant',
    'arada': 'sometimes',
    'sırada': 'waiting',
    'hemen': 'right away',
    'şimdi': 'currently',
    'sonra': 'afterwards',
    'önce': 'previously',
    'bugün': 'nowadays',
    'dün': 'past',
    'yarın': 'future',
    'sabah': 'am',
    'öğle': 'midday',
    'akşam': 'pm',
    'gece': 'late',
    'hafta': 'weekly',
    'ay': 'month',
    'yıl': 'year',
    'gün': 'day',
    'saat': 'hour',
    'dakika': 'minute',
    'saniye': 'second',
    'zaman': 'period',
    'süre': 'duration',
    'an': 'moment',
    'defa': 'time',
    'kere': 'occurrence',
    'kez': 'instance',
    'kişi': 'person',
    'insan': 'human',
    'çocuk': 'child',
    'bebek': 'baby',
    'kadın': 'woman',
    'erkek': 'man',
    'kız': 'girl',
    'erkek': 'boy',
    'genç': 'youth',
    'yaşlı': 'elderly',
    'aile': 'family',
    'arkadaş': 'friend',
    'dost': 'buddy',
    'tanıdık': 'acquaintance',
    'yabancı': 'stranger',
    'müşteri': 'client',
    'satıcı': 'seller',
    'alıcı': 'buyer',
    'tüketici': 'consumer',
    'üretici': 'producer',
    'çalışan': 'worker',
    'işçi': 'laborer',
    'patron': 'boss',
    'müdür': 'director',
    'yönetici': 'executive',
    'lider': 'leader',
    'eleman': 'staff member',
    'personel': 'personnel',
    'ekip': 'team',
    'grup': 'group',
    'topluluk': 'community',
    'şirket': 'company',
    'firma': 'firm',
    'kurum': 'institution',
    'kuruluş': 'organization',
    'mağaza': 'shop',
    'dükkan': 'storefront',
    'market': 'supermarket',
    'avm': 'mall',
    'alışveriş': 'shopping',
    'merkez': 'hub',
    'şube': 'outlet',
    'bayi': 'dealer',
    'acente': 'agency',
    'ofis': 'office',
    'büro': 'bureau',
    'fabrika': 'factory',
    'tesis': 'facility',
    'depo': 'warehouse',
    'ambar': 'storehouse',
    'lojistik': 'logistics',
    'nakliye': 'transport',
    'kargo': 'cargo',
    'kurye': 'courier',
    'teslimat': 'delivery',
    'sipariş': 'order',
    'talep': 'request',
    'istek': 'desire',
    'ihtiyaç': 'need',
    'gereksinim': 'requirement',
    'zorunluluk': 'necessity',
    'tercih': 'preference',
    'seçim': 'choice',
    'karar': 'decision',
    'sonuç': 'result',
    'etki': 'effect',
    'tepki': 'reaction',
    'cevap': 'response',
    'yanıt': 'reply',
    'soru': 'query',
    'sorgu': 'inquiry',
    'araştırma': 'research',
    'inceleme': 'review',
    'değerlendirme': 'evaluation',
    'analiz': 'analysis',
    'rapor': 'report',
    'istatistik': 'statistic',
    'veri': 'data',
    'bilgi': 'information',
    'belge': 'document',
    'dosya': 'file',
    'kayıt': 'record',
    'liste': 'list',
    'tablo': 'table',
    'grafik': 'chart',
    'şema': 'diagram',
    'resim': 'picture',
    'fotoğraf': 'photo',
    'video': 'video',
    'ses': 'audio',
    'müzik': 'song',
    'film': 'movie',
    'dizi': 'series',
    'kitap': 'book',
    'dergi': 'magazine',
    'gazete': 'newspaper',
    'haber': 'news',
    'makale': 'article',
    'yazı': 'text',
    'mesaj': 'message',
    'ileti': 'communication',
    'mektup': 'letter',
    'posta': 'mail',
    'e-posta': 'email',
    'telefon': 'phone',
    'arama': 'call',
    'görüşme': 'interview',
    'toplantı': 'meeting',
    'buluşma': 'gathering',
    'etkinlik': 'event',
    'organizasyon': 'organization',
    'parti': 'party',
    'kutlama': 'celebration',
    'tören': 'ceremony',
    'festival': 'festival',
    'konser': 'concert',
    'tiyatro': 'theater',
    'sinema': 'cinema',
    'sergi': 'exhibition',
    'fuar': 'fair',
    'kongre': 'congress',
    'konferans': 'conference',
    'seminer': 'seminar',
    'kurs': 'course',
    'eğitim': 'education',
    'öğretim': 'teaching',
    'okul': 'school',
    'üniversite': 'university',
    'fakülte': 'faculty',
    'bölüm': 'department',
    'sınıf': 'class',
    'ders': 'lesson',
    'sınav': 'exam',
    'test': 'test',
    'ödev': 'homework',
    'proje': 'project',
    'tez': 'thesis',
    'diploma': 'diploma',
    'sertifika': 'certificate',
    'belge': 'document',
    'lisans': 'license',
    'izin': 'permission',
    'onay': 'approval',
    'kabul': 'acceptance',
    'red': 'rejection',
    'itiraz': 'objection',
    'şikayet': 'complaint',
    'dava': 'lawsuit',
    'mahkeme': 'court',
    'hakim': 'judge',
    'savcı': 'prosecutor',
    'avukat': 'lawyer',
    'polis': 'police',
    'asker': 'soldier',
    'doktor': 'doctor',
    'hemşire': 'nurse',
    'hasta': 'patient',
    'hastane': 'hospital',
    'sağlık': 'health',
    'hastalık': 'disease',
    'ilaç': 'medicine',
    'tedavi': 'treatment',
    'ameliyat': 'surgery',
    'kaza': 'accident',
    'yaralanma': 'injury',
    'ölüm': 'death',
    'doğum': 'birth',
    'yaşam': 'life',
    'hayat': 'life',
    'dünya': 'world',
    'evren': 'universe',
    'doğa': 'nature',
    'çevre': 'environment',
    'iklim': 'climate',
    'hava': 'weather',
    'su': 'water',
    'toprak': 'soil',
    'ateş': 'fire',
    'rüzgar': 'wind',
    'güneş': 'sun',
    'ay': 'moon',
    'yıldız': 'star',
    'gezegen': 'planet',
    'uzay': 'space',
    'zaman': 'time',
    'mekan': 'place',
    'yer': 'location',
    'yön': 'direction',
    'mesafe': 'distance',
    'uzunluk': 'length',
    'genişlik': 'width',
    'yükseklik': 'height',
    'derinlik': 'depth',
    'ağırlık': 'weight',
    'hacim': 'volume',
    'alan': 'area',
    'hız': 'speed',
    'güç': 'power',
    'enerji': 'energy',
    'kuvvet': 'force',
    'hareket': 'movement',
    'durum': 'state',
    'şekil': 'shape',
    'renk': 'color',
    'ses': 'sound',
    'tat': 'taste',
    'koku': 'smell',
    'duygu': 'emotion',
    'düşünce': 'thought',
    'fikir': 'idea',
    'inanç': 'belief',
    'değer': 'value',
    'ahlak': 'morality',
    'din': 'religion',
    'bilim': 'science',
    'sanat': 'art',
    'felsefe': 'philosophy',
    'tarih': 'history',
    'coğrafya': 'geography',
    'matematik': 'math',
    'fizik': 'physics',
    'kimya': 'chemistry',
    'biyoloji': 'biology',
    'tıp': 'medicine',
    'mühendislik': 'engineering',
    'mimarlık': 'architecture',
    'ekonomi': 'economy',
    'işletme': 'business',
    'hukuk': 'law',
    'siyaset': 'politics',
    'spor': 'sports',
    'oyun': 'game',
    'eğlence': 'entertainment',
    'müzik': 'music',
    'sinema': 'cinema',
    'tiyatro': 'theater',
    'edebiyat': 'literature',
    'şiir': 'poetry',
    'roman': 'novel',
    'hikaye': 'story',
    'masal': 'fairy tale',
    'destan': 'epic',
    'efsane': 'legend',
    'mitoloji': 'mythology',
    'din': 'religion',
    'tanrı': 'god',
    'melek': 'angel',
    'şeytan': 'devil',
    'cennet': 'heaven',
    'cehennem': 'hell',
    'ruh': 'soul',
    'beden': 'body',
    'zihin': 'mind',
    'kalp': 'heart',
    'beyin': 'brain',
    'göz': 'eye',
    'kulak': 'ear',
    'burun': 'nose',
    'ağız': 'mouth',
    'dil': 'tongue',
    'diş': 'tooth',
    'dudak': 'lip',
    'yüz': 'face',
    'baş': 'head',
    'saç': 'hair',
    'boyun': 'neck',
    'omuz': 'shoulder',
    'kol': 'arm',
    'el': 'hand',
    'parmak': 'finger',
    'göğüs': 'chest',
    'sırt': 'back',
    'karın': 'stomach',
    'bel': 'waist',
    'kalça': 'hip',
    'bacak': 'leg',
    'diz': 'knee',
    'ayak': 'foot',
    'topuk': 'heel',
    'parmak': 'toe',
    'deri': 'skin',
    'kemik': 'bone',
    'kas': 'muscle',
    'kan': 'blood',
    'damar': 'vein',
    'yürek': 'heart',
    'akciğer': 'lung',
    'karaciğer': 'liver',
    'mide': 'stomach',
    'bağırsak': 'intestine',
    'böbrek': 'kidney',
    'mesane': 'bladder',
    'beyin': 'brain',
    'sinir': 'nerve',
    'hücre': 'cell',
    'gen': 'gene',
    'dna': 'dna',
    'rna': 'rna',
    'protein': 'protein',
    'vitamin': 'vitamin',
    'mineral': 'mineral',
    'karbonhidrat': 'carbohydrate',
    'yağ': 'fat',
    'su': 'water',
    'oksijen': 'oxygen',
    'karbondioksit': 'carbon dioxide',
    'azot': 'nitrogen',
    'hidrojen': 'hydrogen',
    'demir': 'iron',
    'kalsiyum': 'calcium',
    'sodyum': 'sodium',
    'potasyum': 'potassium',
    'magnezyum': 'magnesium',
    'çinko': 'zinc',
    'bakır': 'copper',
    'iyot': 'iodine',
    'flor': 'fluorine',
    'klor': 'chlorine',
    'kükürt': 'sulfur',
    'fosfor': 'phosphorus',
    'altın': 'gold',
    'gümüş': 'silver',
    'platin': 'platinum',
    'elmas': 'diamond',
    'yakut': 'ruby',
    'zümrüt': 'emerald',
    'safir': 'sapphire',
    'inci': 'pearl',
    'mercan': 'coral',
    'kehribar': 'amber',
    'yeşim': 'jade',
    'opal': 'opal',
    'turkuaz': 'turquoise',
    'ametist': 'amethyst',
    'kuvars': 'quartz',
    'granit': 'granite',
    'mermer': 'marble',
    'kireçtaşı': 'limestone',
    'kumtaşı': 'sandstone',
    'kil': 'clay',
    'kum': 'sand',
    'çakıl': 'gravel',
    'toprak': 'soil',
    'çamur': 'mud',
    'toz': 'dust',
    'kül': 'ash',
    'duman': 'smoke',
    'buhar': 'steam',
    'sis': 'fog',
    'bulut': 'cloud',
    'yağmur': 'rain',
    'kar': 'snow',
    'dolu': 'hail',
    'buz': 'ice',
    'kırağı': 'frost',
    'çiğ': 'dew',
    'rüzgar': 'wind',
    'fırtına': 'storm',
    'kasırga': 'hurricane',
    'hortum': 'tornado',
    'deprem': 'earthquake',
    'tsunami': 'tsunami',
    'yanardağ': 'volcano',
    'sel': 'flood',
    'heyelan': 'landslide',
    'çığ': 'avalanche',
    'orman': 'forest',
    'ağaç': 'tree',
    'yaprak': 'leaf',
    'dal': 'branch',
    'kök': 'root',
    'çiçek': 'flower',
    'meyve': 'fruit',
    'sebze': 'vegetable',
    'ot': 'grass',
    'tohum': 'seed',
    'hayvan': 'animal',
    'kuş': 'bird',
    'balık': 'fish',
    'böcek': 'insect',
    'sürüngen': 'reptile',
    'memeli': 'mammal',
    'kedi': 'cat',
    'köpek': 'dog',
    'at': 'horse',
    'inek': 'cow',
    'koyun': 'sheep',
    'keçi': 'goat',
    'domuz': 'pig',
    'tavuk': 'chicken',
    'ördek': 'duck',
    'kaz': 'goose',
    'hindi': 'turkey',
    'tavşan': 'rabbit',
    'fare': 'mouse',
    'sıçan': 'rat',
    'yılan': 'snake',
    'kertenkele': 'lizard',
    'timsah': 'crocodile',
    'kaplumbağa': 'turtle',
    'kurbağa': 'frog',
    'balina': 'whale',
    'yunus': 'dolphin',
    'köpekbalığı': 'shark',
    'ahtapot': 'octopus',
    'kalamar': 'squid',
    'yengeç': 'crab',
    'ıstakoz': 'lobster',
    'karides': 'shrimp',
    'midye': 'mussel',
    'istiridye': 'oyster',
    'salyangoz': 'snail',
    'solucan': 'worm',
    'arı': 'bee',
    'karınca': 'ant',
    'sinek': 'fly',
    'sivrisinek': 'mosquito',
    'kelebek': 'butterfly',
    'güve': 'moth',
    'örümcek': 'spider',
    'akrep': 'scorpion',
    'kene': 'tick',
    'pire': 'flea',
    'bit': 'louse',
    'tahtakurusu': 'bedbug',
    'hamamböceği': 'cockroach',
    'çekirge': 'grasshopper',
    'cırcırböceği': 'cricket',
    'ağustosböceği': 'cicada',
    'peygamberdevesi': 'mantis',
    'uğurböceği': 'ladybug',
    'ateşböceği': 'firefly',
    'yusufçuk': 'dragonfly',
    'kırkayak': 'centipede',
    'çıyan': 'millipede',
    'sülük': 'leech',
    'denizanası': 'jellyfish',
    'denizyıldızı': 'starfish',
    'denizkestanesi': 'sea urchin',
    'denizhıyarı': 'sea cucumber',
    'sünger': 'sponge',
    'mercan': 'coral',
    'yosun': 'algae',
    'mantar': 'mushroom',
    'bakteri': 'bacteria',
    'virüs': 'virus',
    'mikrop': 'microbe',
    'parazit': 'parasite',
    'enfeksiyon': 'infection',
    'hastalık': 'disease',
    'sağlık': 'health',
    'tıp': 'medicine',
    'doktor': 'doctor',
    'hemşire': 'nurse',
    'hasta': 'patient',
    'hastane': 'hospital',
    'klinik': 'clinic',
    'eczane': 'pharmacy',
    'ilaç': 'medicine',
    'hap': 'pill',
    'şurup': 'syrup',
    'iğne': 'injection',
    'serum': 'serum',
    'aşı': 'vaccine',
    'ameliyat': 'surgery',
    'operasyon': 'operation',
    'tedavi': 'treatment',
    'teşhis': 'diagnosis',
    'muayene': 'examination',
    'tahlil': 'analysis',
    'röntgen': 'x-ray',
    'ultrason': 'ultrasound',
    'emar': 'mri',
    'tomografi': 'ct scan',
    'kan': 'blood',
    'idrar': 'urine',
    'dışkı': 'feces',
    'tükürük': 'saliva',
    'ter': 'sweat',
    'gözyaşı': 'tear',
    'sümük': 'mucus',
    'balgam': 'phlegm',
    'kusmuk': 'vomit',
    'irin': 'pus',
    'yara': 'wound',
    'bere': 'bruise',
    'çizik': 'scratch',
    'kesik': 'cut',
    'yanık': 'burn',
    'kırık': 'fracture',
    'çıkık': 'dislocation',
    'burkulma': 'sprain',
    'ezik': 'crush',
    'şişlik': 'swelling',
    'morluk': 'bruise',
    'kızarıklık': 'redness',
    'kaşıntı': 'itching',
    'ağrı': 'pain',
    'sızı': 'ache',
    'acı': 'hurt',
    'ateş': 'fever',
    'titreme': 'shivering',
    'terleme': 'sweating',
    'öksürük': 'cough',
    'hapşırık': 'sneeze',
    'hıçkırık': 'hiccup',
    'esneme': 'yawn',
    'geğirme': 'burp',
    'osuruk': 'fart',
    'nefes': 'breath',
    'solunum': 'respiration',
    'nabız': 'pulse',
    'tansiyon': 'blood pressure',
    'kalp': 'heart',
    'damar': 'vein',
    'kan': 'blood',
    'beyin': 'brain',
    'sinir': 'nerve',
    'omurilik': 'spinal cord',
    'kas': 'muscle',
    'kemik': 'bone',
    'eklem': 'joint',
    'kıkırdak': 'cartilage',
    'deri': 'skin',
    'saç': 'hair',
    'kıl': 'hair',
    'tırnak': 'nail',
    'diş': 'tooth',
    'dil': 'tongue',
    'dudak': 'lip',
    'ağız': 'mouth',
    'burun': 'nose',
    'göz': 'eye',
    'kulak': 'ear',
    'yüz': 'face',
    'baş': 'head',
    'boyun': 'neck',
    'omuz': 'shoulder',
    'kol': 'arm',
    'el': 'hand',
    'parmak': 'finger',
    'göğüs': 'chest',
    'sırt': 'back',
    'karın': 'stomach',
    'bel': 'waist',
    'kalça': 'hip',
    'bacak': 'leg',
    'diz': 'knee',
    'ayak': 'foot',
    'topuk': 'heel',
    'mide': 'stomach',
    'bağırsak': 'intestine',
    'karaciğer': 'liver',
    'böbrek': 'kidney',
    'akciğer': 'lung',
    'dalak': 'spleen',
    'pankreas': 'pancreas',
    'safra': 'bile',
    'mesane': 'bladder',
    'rahim': 'uterus',
    'yumurtalık': 'ovary',
    'testis': 'testicle',
    'prostat': 'prostate',
    'hormon': 'hormone',
    'enzim': 'enzyme',
    'hücre': 'cell',
    'doku': 'tissue',
    'organ': 'organ',
    'sistem': 'system',
    'vücut': 'body',
    'canlı': 'living',
    'cansız': 'non-living',
    'hayat': 'life',
    'ölüm': 'death',
    'doğum': 'birth',
    'yaş': 'age',
    'genç': 'young',
    'yaşlı': 'old',
    'çocuk': 'child',
    'bebek': 'baby',
    'yetişkin': 'adult',
    'erkek': 'male',
    'kadın': 'female',
    'insan': 'human',
    'hayvan': 'animal',
    'bitki': 'plant',
    'doğa': 'nature',
    'çevre': 'environment',
    'dünya': 'world',
    'evren': 'universe',
    'uzay': 'space',
    'zaman': 'time',
    'mekan': 'place',
    'madde': 'matter',
    'enerji': 'energy',
    'güç': 'power',
    'kuvvet': 'force',
    'hareket': 'motion',
    'hız': 'speed',
    'ivme': 'acceleration',
    'kütle': 'mass',
    'ağırlık': 'weight',
    'hacim': 'volume',
    'yoğunluk': 'density',
    'sıcaklık': 'temperature',
    'basınç': 'pressure',
    'ışık': 'light',
    'ses': 'sound',
    'elektrik': 'electricity',
    'manyetizma': 'magnetism',
    'yerçekimi': 'gravity',
    'atom': 'atom',
    'molekül': 'molecule',
    'element': 'element',
    'bileşik': 'compound',
    'karışım': 'mixture',
    'çözelti': 'solution',
    'asit': 'acid',
    'baz': 'base',
    'tuz': 'salt',
    'su': 'water',
    'hava': 'air',
    'toprak': 'earth',
    'ateş': 'fire',
    'güneş': 'sun',
    'ay': 'moon',
    'yıldız': 'star',
    'gezegen': 'planet',
    'galaksi': 'galaxy',
    'kara': 'land',
    'deniz': 'sea',
    'okyanus': 'ocean',
    'göl': 'lake',
    'nehir': 'river',
    'dağ': 'mountain',
    'tepe': 'hill',
    'vadi': 'valley',
    'ova': 'plain',
    'çöl': 'desert',
    'orman': 'forest',
    'ada': 'island',
    'kıta': 'continent',
    'ülke': 'country',
    'şehir': 'city',
    'kasaba': 'town',
    'köy': 'village',
    'sokak': 'street',
    'cadde': 'avenue',
    'meydan': 'square',
    'park': 'park',
    'bahçe': 'garden',
    'ev': 'house',
    'bina': 'building',
    'apartman': 'apartment',
    'oda': 'room',
    'salon': 'living room',
    'mutfak': 'kitchen',
    'banyo': 'bathroom',
    'tuvalet': 'toilet',
    'yatak': 'bed',
    'masa': 'table',
    'sandalye': 'chair',
    'koltuk': 'sofa',
    'dolap': 'closet',
    'kapı': 'door',
    'pencere': 'window',
    'duvar': 'wall',
    'tavan': 'ceiling',
    'zemin': 'floor',
    'çatı': 'roof',
    'merdiven': 'stairs',
    'asansör': 'elevator',
    'araba': 'car',
    'otobüs': 'bus',
    'kamyon': 'truck',
    'tren': 'train',
    'uçak': 'airplane',
    'gemi': 'ship',
    'bisiklet': 'bicycle',
    'motosiklet': 'motorcycle',
    'yol': 'road',
    'köprü': 'bridge',
    'tünel': 'tunnel',
    'kavşak': 'intersection',
    'trafik': 'traffic',
    'işaret': 'sign',
    'lamba': 'lamp',
    'ışık': 'light',
    'renk': 'color',
    'kırmızı': 'red',
    'mavi': 'blue',
    'sarı': 'yellow',
    'yeşil': 'green',
    'turuncu': 'orange',
    'mor': 'purple',
    'pembe': 'pink',
    'kahverengi': 'brown',
    'siyah': 'black',
    'beyaz': 'white',
    'gri': 'gray',
    'sayı': 'number',
    'rakam': 'digit',
    'sıfır': 'zero',
    'bir': 'one',
    'iki': 'two',
    'üç': 'three',
    'dört': 'four',
    'beş': 'five',
    'altı': 'six',
    'yedi': 'seven',
    'sekiz': 'eight',
    'dokuz': 'nine',
    'on': 'ten',
    'yüz': 'hundred',
    'bin': 'thousand',
    'milyon': 'million',
    'milyar': 'billion',
    'para': 'money',
    'lira': 'lira',
    'dolar': 'dollar',
    'euro': 'euro',
    'kuruş': 'cent',
    'banka': 'bank',
    'hesap': 'account',
    'kredi': 'credit',
    'borç': 'debt',
    'faiz': 'interest',
    'vergi': 'tax',
    'fiyat': 'price',
    'maliyet': 'cost',
    'kar': 'profit',
    'zarar': 'loss',
    'gelir': 'income',
    'gider': 'expense',
    'maaş': 'salary',
    'ücret': 'wage',
    'fatura': 'invoice',
    'fiş': 'receipt',
    'çek': 'check',
    'senet': 'bill',
    'sözleşme': 'contract',
    'imza': 'signature',
    'mühür': 'seal',
    'belge': 'document',
    'dosya': 'file',
    'kağıt': 'paper',
    'kalem': 'pen',
    'kitap': 'book',
    'defter': 'notebook',
    'dergi': 'magazine',
    'gazete': 'newspaper',
    'mektup': 'letter',
    'zarf': 'envelope',
    'pul': 'stamp',
    'paket': 'package',
    'kutu': 'box',
    'çanta': 'bag',
    'valiz': 'suitcase',
    'anahtar': 'key',
    'kilit': 'lock',
    'saat': 'clock',
    'gözlük': 'glasses',
    'şemsiye': 'umbrella',
    'ayakkabı': 'shoe',
    'çorap': 'sock',
    'pantolon': 'pants',
    'gömlek': 'shirt',
    'ceket': 'jacket',
    'kaban': 'coat',
    'şapka': 'hat',
    'eldiven': 'glove',
    'atkı': 'scarf',
    'kravat': 'tie',
    'kemer': 'belt',
    'elbise': 'dress',
    'etek': 'skirt',
    'bluz': 'blouse',
    'kazak': 'sweater',
    'tişört': 't-shirt',
    'şort': 'shorts',
    'mayo': 'swimsuit',
    'pijama': 'pajamas',
    'iç': 'inner',
    'çamaşır': 'laundry',
    'havlu': 'towel',
    'battaniye': 'blanket',
    'yastık': 'pillow',
    'yorgan': 'quilt',
    'çarşaf': 'sheet',
    'halı': 'carpet',
    'kilim': 'rug',
    'perde': 'curtain',
    'tablo': 'painting',
    'ayna': 'mirror',
    'vazo': 'vase',
    'çiçek': 'flower',
    'bitki': 'plant',
    'ağaç': 'tree',
    'yaprak': 'leaf',
    'dal': 'branch',
    'kök': 'root',
    'meyve': 'fruit',
    'sebze': 'vegetable',
    'et': 'meat',
    'tavuk': 'chicken',
    'balık': 'fish',
    'yumurta': 'egg',
    'süt': 'milk',
    'peynir': 'cheese',
    'yoğurt': 'yogurt',
    'tereyağı': 'butter',
    'zeytinyağı': 'olive oil',
    'ekmek': 'bread',
    'su': 'water',
    'çay': 'tea',
    'kahve': 'coffee',
    'meyve': 'fruit',
    'suyu': 'juice',
    'şarap': 'wine',
    'bira': 'beer',
    'rakı': 'raki',
    'şeker': 'sugar',
    'tuz': 'salt',
    'biber': 'pepper',
    'baharat': 'spice',
    'tatlı': 'sweet',
    'acı': 'bitter',
    'ekşi': 'sour',
    'tuzlu': 'salty',
    'sıcak': 'hot',
    'soğuk': 'cold',
    'ılık': 'warm',
    'taze': 'fresh',
    'bayat': 'stale',
    'çiğ': 'raw',
    'pişmiş': 'cooked',
    'kızarmış': 'fried',
    'haşlanmış': 'boiled',
    'fırınlanmış': 'baked',
    'ızgara': 'grilled',
    'yemek': 'food',
    'kahvaltı': 'breakfast',
    'öğle': 'lunch',
    'akşam': 'dinner',
    'öğün': 'meal',
    'tabak': 'plate',
    'kase': 'bowl',
    'bardak': 'glass',
    'fincan': 'cup',
    'çatal': 'fork',
    'bıçak': 'knife',
    'kaşık': 'spoon',
    'tencere': 'pot',
    'tava': 'pan',
    'tepsi': 'tray',
    'ocak': 'stove',
    'fırın': 'oven',
    'buzdolabı': 'refrigerator',
    'bulaşık': 'dish',
    'makinesi': 'machine',
    'çamaşır': 'washing',
    'ütü': 'iron',
    'süpürge': 'vacuum',
    'televizyon': 'television',
    'radyo': 'radio',
    'bilgisayar': 'computer',
    'telefon': 'phone',
    'tablet': 'tablet',
    'kamera': 'camera',
    'kulaklık': 'headphone',
    'hoparlör': 'speaker',
    'pil': 'battery',
    'şarj': 'charge',
    'kablo': 'cable',
    'priz': 'socket',
    'fiş': 'plug',
    'ampul': 'bulb',
    'ışık': 'light',
    'elektrik': 'electricity',
    'su': 'water',
    'gaz': 'gas',
    'ısınma': 'heating',
    'soğutma': 'cooling',
    'temizlik': 'cleaning',
    'bakım': 'maintenance',
    'onarım': 'repair',
    'tamir': 'fix',
    'inşaat': 'construction',
    'yıkım': 'demolition',
    'boya': 'paint',
    'badana': 'whitewash',
    'tesisat': 'plumbing',
    'marangoz': 'carpenter',
    'demirci': 'blacksmith',
    'elektrikçi': 'electrician',
    'tesisatçı': 'plumber',
    'boyacı': 'painter',
    'işçi': 'worker',
    'usta': 'master',
    'çırak': 'apprentice',
    'mühendis': 'engineer',
    'mimar': 'architect',
    'doktor': 'doctor',
    'hemşire': 'nurse',
    'öğretmen': 'teacher',
    'öğrenci': 'student',
    'polis': 'police',
    'asker': 'soldier',
    'avukat': 'lawyer',
    'hakim': 'judge',
    'savcı': 'prosecutor',
    'memur': 'officer',
    'müdür': 'manager',
    'patron': 'boss',
    'işçi': 'worker',
    'çiftçi': 'farmer',
    'esnaf': 'tradesman',
    'tüccar': 'merchant',
    'sanatçı': 'artist',
    'yazar': 'writer',
    'şair': 'poet',
    'müzisyen': 'musician',
    'oyuncu': 'actor',
    'şarkıcı': 'singer',
    'ressam': 'painter',
    'heykeltıraş': 'sculptor',
    'mimar': 'architect',
    'mühendis': 'engineer',
    'doktor': 'doctor',
    'dişçi': 'dentist',
    'veteriner': 'veterinarian',
    'eczacı': 'pharmacist',
    'psikolog': 'psychologist',
    'sosyolog': 'sociologist',
    'tarihçi': 'historian',
    'coğrafyacı': 'geographer',
    'matematikçi': 'mathematician',
    'fizikçi': 'physicist',
    'kimyacı': 'chemist',
    'biyolog': 'biologist',
    'astronom': 'astronomer',
    'filozof': 'philosopher',
    'din': 'religion',
    'adamı': 'man',
    'siyasetçi': 'politician',
    'bakan': 'minister',
    'başbakan': 'prime minister',
    'cumhurbaşkanı': 'president',
    'kral': 'king',
    'kraliçe': 'queen',
    'prens': 'prince',
    'prenses': 'princess',
    'asker': 'soldier',
    'komutan': 'commander',
    'general': 'general',
    'amiral': 'admiral',
    'subay': 'officer',
    'astsubay': 'non-commissioned officer',
    'er': 'private',
    'polis': 'police',
    'komiser': 'commissioner',
    'müfettiş': 'inspector',
    'dedektif': 'detective',
    'bekçi': 'guard',
    'güvenlik': 'security',
    'hırsız': 'thief',
    'katil': 'killer',
    'suçlu': 'criminal',
    'mahkum': 'prisoner',
    'kurban': 'victim',
    'tanık': 'witness',
    'şüpheli': 'suspect',
    'sanık': 'defendant',
    'davacı': 'plaintiff',
    'davalı': 'defendant',
    'avukat': 'lawyer',
    'hakim': 'judge',
    'savcı': 'prosecutor',
    'mahkeme': 'court',
    'dava': 'lawsuit',
    'ceza': 'punishment',
    'hapis': 'prison',
    'idam': 'execution',
    'af': 'amnesty',
    'adalet': 'justice',
    'hukuk': 'law',
    'yasa': 'law',
    'kanun': 'statute',
    'kural': 'rule',
    'nizam': 'order',
    'düzen': 'system',
    'devlet': 'state',
    'hükümet': 'government',
    'millet': 'nation',
    'halk': 'people',
    'toplum': 'society',
    'birey': 'individual',
    'aile': 'family',
    'akraba': 'relative',
    'arkadaş': 'friend',
    'dost': 'friend',
    'düşman': 'enemy',
    'rakip': 'rival',
    'ortak': 'partner',
    'yardımcı': 'assistant',
    'destekçi': 'supporter',
    'karşıt': 'opponent',
    'taraftar': 'fan',
    'üye': 'member',
    'başkan': 'president',
    'lider': 'leader',
    'yönetici': 'manager',
    'müdür': 'director',
    'şef': 'chief',
    'patron': 'boss',
    'işçi': 'worker',
    'memur': 'officer',
    'hizmetçi': 'servant',
    'köle': 'slave',
    'efendi': 'master',
    'sahip': 'owner',
    'kiracı': 'tenant',
    'ev': 'house',
    'sahibi': 'owner',
    'misafir': 'guest',
    'yolcu': 'passenger',
    'turist': 'tourist',
    'ziyaretçi': 'visitor',
    'müşteri': 'customer',
    'satıcı': 'seller',
    'alıcı': 'buyer',
    'tüketici': 'consumer',
    'üretici': 'producer',
    'işveren': 'employer',
    'işgören': 'employee',
    'işsiz': 'unemployed',
    'emekli': 'retired',
    'öğrenci': 'student',
    'öğretmen': 'teacher',
    'okul': 'school',
    'sınıf': 'class',
    'ders': 'lesson',
    'sınav': 'exam',
    'not': 'grade',
    'karne': 'report card',
    'diploma': 'diploma',
    'mezun': 'graduate',
    'üniversite': 'university',
    'fakülte': 'faculty',
    'bölüm': 'department',
    'kampüs': 'campus',
    'yurt': 'dormitory',
    'kütüphane': 'library',
    'kitap': 'book',
    'defter': 'notebook',
    'kalem': 'pen',
    'silgi': 'eraser',
    'çanta': 'bag',
    'sıra': 'desk',
    'tahta': 'board',
    'tebeşir': 'chalk',
    'bilgisayar': 'computer',
    'internet': 'internet',
    'web': 'web',
    'site': 'site',
    'sayfa': 'page',
    'link': 'link',
    'bağlantı': 'connection',
    'ağ': 'network',
    'sunucu': 'server',
    'istemci': 'client',
    'yazılım': 'software',
    'donanım': 'hardware',
    'program': 'program',
    'uygulama': 'application',
    'oyun': 'game',
    'video': 'video',
    'müzik': 'music',
    'resim': 'picture',
    'fotoğraf': 'photo',
    'dosya': 'file',
    'klasör': 'folder',
    'belge': 'document',
    'metin': 'text',
    'yazı': 'writing',
    'harf': 'letter',
    'kelime': 'word',
    'cümle': 'sentence',
    'paragraf': 'paragraph',
    'sayfa': 'page',
    'bölüm': 'chapter',
    'kitap': 'book',
    'dergi': 'magazine',
    'gazete': 'newspaper',
    'haber': 'news',
    'makale': 'article',
    'yazar': 'writer',
    'okur': 'reader',
    'yayın': 'publication',
    'basım': 'printing',
    'dağıtım': 'distribution',
    'satış': 'sale',
    'pazarlama': 'marketing',
    'reklam': 'advertising',
    'tanıtım': 'promotion',
    'kampanya': 'campaign',
    'indirim': 'discount',
    'fiyat': 'price',
    'ücret': 'fee',
    'bedel': 'cost',
    'değer': 'value',
    'kalite': 'quality',
    'marka': 'brand',
    'model': 'model',
    'çeşit': 'variety',
    'renk': 'color',
    'beden': 'size',
    'ölçü': 'measure',
    'ağırlık': 'weight',
    'uzunluk': 'length',
    'genişlik': 'width',
    'yükseklik': 'height',
    'derinlik': 'depth',
    'hacim': 'volume',
    'alan': 'area',
    'zaman': 'time',
    'hız': 'speed',
    'sıcaklık': 'temperature',
    'basınç': 'pressure',
    'enerji': 'energy',
    'güç': 'power',
    'kuvvet': 'force',
    'hareket': 'motion',
    'durum': 'state',
    'şekil': 'shape',
    'biçim': 'form',
    'yapı': 'structure',
    'sistem': 'system',
    'düzen': 'order',
    'kural': 'rule',
    'yasa': 'law',
    'ilke': 'principle',
    'teori': 'theory',
    'pratik': 'practice',
    'deney': 'experiment',
    'gözlem': 'observation',
    'araştırma': 'research',
    'inceleme': 'examination',
    'analiz': 'analysis',
    'sentez': 'synthesis',
    'değerlendirme': 'evaluation',
    'sonuç': 'result',
    'karar': 'decision',
    'seçim': 'choice',
    'tercih': 'preference',
    'istek': 'desire',
    'ihtiyaç': 'need',
    'amaç': 'purpose',
    'hedef': 'goal',
    'plan': 'plan',
    'proje': 'project',
    'program': 'program',
    'görev': 'task',
    'iş': 'work',
    'meslek': 'profession',
    'kariyer': 'career',
    'başarı': 'success',
    'başarısızlık': 'failure',
    'zafer': 'victory',
    'yenilgi': 'defeat',
    'kazanç': 'gain',
    'kayıp': 'loss',
    'kar': 'profit',
    'zarar': 'damage',
    'gelir': 'income',
    'gider': 'expense',
    'bütçe': 'budget',
    'ekonomi': 'economy',
    'finans': 'finance',
    'para': 'money',
    'banka': 'bank',
    'kredi': 'credit',
    'borç': 'debt',
    'faiz': 'interest',
    'vergi': 'tax',
    'fatura': 'invoice',
    'fiş': 'receipt',
    'ödeme': 'payment',
    'tahsilat': 'collection',
    'alış': 'purchase',
    'satış': 'sale',
    'ticaret': 'trade',
    'pazar': 'market',
    'mağaza': 'store',
    'dükkan': 'shop',
    'müşteri': 'customer',
    'satıcı': 'seller',
    'ürün': 'product',
    'mal': 'goods',
    'hizmet': 'service',
    'kalite': 'quality',
    'garanti': 'warranty',
    'iade': 'return',
    'değişim': 'exchange',
    'şikayet': 'complaint',
    'memnuniyet': 'satisfaction',
    'öneri': 'suggestion',
    'tavsiye': 'recommendation',
    'teşekkür': 'thanks',
    'özür': 'apology',
    'selam': 'greeting',
    'veda': 'farewell',
    'merhaba': 'hello',
    'hoşça': 'goodbye',
    'kal': 'stay',
    'git': 'go',
    'gel': 'come',
    'dur': 'stop',
    'koş': 'run',
    'yürü': 'walk',
    'otur': 'sit',
    'kalk': 'stand',
    'yat': 'lie',
    'uyu': 'sleep',
    'uyan': 'wake',
    'ye': 'eat',
    'iç': 'drink',
    'gör': 'see',
    'duy': 'hear',
    'kokla': 'smell',
    'tat': 'taste',
    'dokun': 'touch',
    'hisset': 'feel',
    'düşün': 'think',
    'anla': 'understand',
    'bil': 'know',
    'öğren': 'learn',
    'öğret': 'teach',
    'oku': 'read',
    'yaz': 'write',
    'konuş': 'speak',
    'dinle': 'listen',
    'sor': 'ask',
    'cevapla': 'answer',
    'söyle': 'say',
    'anlat': 'tell',
    'açıkla': 'explain',
    'göster': 'show',
    'gizle': 'hide',
    'bul': 'find',
    'kaybet': 'lose',
    'al': 'take',
    'ver': 'give',
    'tut': 'hold',
    'bırak': 'drop',
    'at': 'throw',
    'çek': 'pull',
    'it': 'push',
    'kaldır': 'lift',
    'indir': 'lower',
    'aç': 'open',
    'kapat': 'close',
    'kilitle': 'lock',
    'çöz': 'solve',
    'bağla': 'tie',
    'kes': 'cut',
    'böl': 'divide',
    'birleştir': 'join',
    'ayır': 'separate',
    'ekle': 'add',
    'çıkar': 'subtract',
    'çarp': 'multiply',
    'say': 'count',
    'ölç': 'measure',
    'tart': 'weigh',
    'değerlendir': 'evaluate',
    'karşılaştır': 'compare',
    'seç': 'choose',
    'karar': 'decide',
    'ver': 'give',
    'planla': 'plan',
    'yap': 'do',
    'et': 'make',
    'ol': 'be',
    'var': 'exist',
    'yok': 'not exist',
    'başla': 'start',
    'bitir': 'finish',
    'devam': 'continue',
    'durakla': 'pause',
    'bekle': 'wait',
    'acele': 'hurry',
    'gecik': 'delay',
    'ertele': 'postpone',
    'iptal': 'cancel',
    'onayla': 'approve',
    'reddet': 'reject',
    'kabul': 'accept',
    'itiraz': 'object',
    'şikayet': 'complain',
    'teşekkür': 'thank',
    'özür': 'apologize',
    'affet': 'forgive',
    'cezalandır': 'punish',
    'ödüllendir': 'reward',
    'sev': 'love',
    'nefret': 'hate',
    'kork': 'fear',
    'cesaret': 'courage',
    'umut': 'hope',
    'üzül': 'sad',
    'sevin': 'happy',
    'ağla': 'cry',
    'gül': 'laugh',
    'gülümse': 'smile',
    'kız': 'angry',
    'şaşır': 'surprised',
    'heyecan': 'excited',
    'sakin': 'calm',
    'rahat': 'comfortable',
    'huzur': 'peace',
    'stres': 'stress',
    'yorgun': 'tired',
    'dinç': 'energetic',
    'hasta': 'sick',
    'sağlam': 'healthy',
    'güçlü': 'strong',
    'zayıf': 'weak',
    'şişman': 'fat',
    'ince': 'thin',
    'uzun': 'tall',
    'kısa': 'short',
    'büyük': 'big',
    'küçük': 'small',
    'geniş': 'wide',
    'dar': 'narrow',
    'kalın': 'thick',
    'ince': 'thin',
    'ağır': 'heavy',
    'hafif': 'light',
    'sıcak': 'hot',
    'soğuk': 'cold',
    'ılık': 'warm',
    'serin': 'cool',
    'kuru': 'dry',
    'ıslak': 'wet',
    'nemli': 'damp',
    'sert': 'hard',
    'yumuşak': 'soft',
    'pürüzsüz': 'smooth',
    'pürüzlü': 'rough',
    'düz': 'flat',
    'eğri': 'curved',
    'yuvarlak': 'round',
    'kare': 'square',
    'dikdörtgen': 'rectangle',
    'üçgen': 'triangle',
    'renkli': 'colorful',
    'renksiz': 'colorless',
    'parlak': 'bright',
    'mat': 'matte',
    'karanlık': 'dark',
    'aydınlık': 'light',
    'sesli': 'loud',
    'sessiz': 'quiet',
    'hızlı': 'fast',
    'yavaş': 'slow',
    'erken': 'early',
    'geç': 'late',
    'yeni': 'new',
    'eski': 'old',
    'genç': 'young',
    'yaşlı': 'old',
    'iyi': 'good',
    'kötü': 'bad',
    'güzel': 'beautiful',
    'çirkin': 'ugly',
    'doğru': 'right',
    'yanlış': 'wrong',
    'gerçek': 'true',
    'yalan': 'false',
    'kolay': 'easy',
    'zor': 'difficult',
    'basit': 'simple',
    'karmaşık': 'complex',
    'ucuz': 'cheap',
    'pahalı': 'expensive',
    'zengin': 'rich',
    'fakir': 'poor',
    'dolu': 'full',
    'boş': 'empty',
    'açık': 'open',
    'kapalı': 'closed',
    'temiz': 'clean',
    'pis': 'dirty',
    'düzenli': 'tidy',
    'dağınık': 'messy',
    'güvenli': 'safe',
    'tehlikeli': 'dangerous',
    'önemli': 'important',
    'önemsiz': 'unimportant',
    'gerekli': 'necessary',
    'gereksiz': 'unnecessary',
    'faydalı': 'useful',
    'zararlı': 'harmful',
    'aynı': 'same',
    'farklı': 'different',
    'benzer': 'similar',
    'ayrı': 'separate',
    'birlikte': 'together',
    'yalnız': 'alone',
    'tek': 'single',
    'çift': 'double',
    'çok': 'many',
    'az': 'few',
    'bütün': 'all',
    'bazı': 'some',
    'hiçbir': 'none',
    'her': 'every',
    'başka': 'other',
    'kendi': 'own',
    'şubesi': 'branch',
    'sevkiyat': 'shipment',
    'geçti': 'passed',
    'geliyor': 'coming',
    'yoğun': 'busy',
    'yorucu': 'tiring',
    'verimli': 'productive',
    'prim': 'bonus',
    'yüksek': 'high',
    'haftaydı': 'week',
    'hedefler': 'targets',
    'hedef': 'target',
    'teşekkürler': 'thanks',
    'seviyorum': 'love',
    'merhabalar': 'hello',
    'rağmen': 'despite',
    'geçirdik': 'spent',
    'istiyorum': 'want',
    'hissediyorum': 'feel',
    'düşük': 'low',
    'aşırı': 'extreme',
    'sayım': 'inventory',
    'buna': 'to this',
    'yinede': 'still',
    'iyileştirme': 'improvement',
    'istiyoruz': 'we want',
    'hasarlı': 'damaged',
    'hasar': 'damage',
    'eksik': 'missing',
    'fazla': 'too much',
    'yetersiz': 'insufficient',
    'yeterli': 'sufficient',
    'bekledik': 'waited',
    'bekleme': 'waiting',
    'bulamadım': 'could not find',
    'yoktu': 'was not there',
    'vardı': 'was there',
    'görevli': 'attendant',
    'müşteri': 'customer',
    'memnuniyet': 'satisfaction',
    'şikayet': 'complaint',
    'öneri': 'suggestion',
    'kaba': 'rude',
    'saygılı': 'respectful',
    'ilgili': 'attentive',
    'ilgisiz': 'inattentive',
    'güleryüz': 'smiling face',
    'suratsız': 'sullen',
    'yardımsever': 'helpful',
    'deneme': 'fitting',
    'kabini': 'room',
    'kabin': 'cabin',
    'reyon': 'aisle',
    'raf': 'shelf',
    'düzen': 'order',
    'tertip': 'neatness',
    'ferah': 'spacious',
    'dar': 'narrow',
    'geniş': 'wide',
    'aydınlık': 'bright',
    'koku': 'smell',
    'havalandırma': 'ventilation',
    'klima': 'ac',
    'çalışmıyor': 'not working',
    'bozuk': 'broken',
    'eski': 'old',
    'yeni': 'new',
    'moda': 'fashion',
    'tarz': 'style',
    'model': 'model',
    'seçenek': 'option',
    'alternatif': 'alternative',
    'stok': 'stock',
    'tükendi': 'sold out',
    'kalmadı': 'out of stock',
    'geldi': 'arrived',
    'gelecek': 'will arrive',
    'iade': 'return',
    'değişim': 'exchange',
    'fiş': 'receipt',
    'fatura': 'invoice',
    'kredi': 'credit',
    'kartı': 'card',
    'nakit': 'cash',
    'ödeme': 'payment',
    'sistem': 'system',
    'yavaşlık': 'slowness',
    'hız': 'speed',
    'pratik': 'practical',
    'çözüm': 'solution',
    'odaklı': 'oriented',
    'sorun': 'problem',
    'problem': 'problem',
    'sıkıntı': 'trouble',
    'hata': 'error',
    'yanlış': 'wrong',
    'doğru': 'right',
    'tam': 'complete',
    'yarım': 'half',
    'tavsiye': 'recommend',
    'ederim': 'I do',
    'etmem': 'I do not',
    'kesinlikle': 'absolutely',
    'asla': 'never',
    'her': 'every',
    'zaman': 'time',
    'bazen': 'sometimes',
    'hiç': 'never',
    'sürekli': 'constantly',
    'devamlı': 'continuously',
    'arada': 'occasionally',
    'sırada': 'in line',
    'hemen': 'immediately',
    'şimdi': 'now',
    'sonra': 'later',
    'önce': 'before',
    'bugün': 'today',
    'dün': 'yesterday',
    'yarın': 'tomorrow',
    'sabah': 'morning',
    'öğle': 'noon',
    'akşam': 'evening',
    'gece': 'night',
    'hafta': 'week',
    'sonu': 'end',
    'içi': 'inside',
    'dışı': 'outside',
    'yakın': 'near',
    'uzak': 'far',
    'merkez': 'center',
    'şube': 'branch',
    'mağazası': 'store',
    'çalışanı': 'employee',
    'müdürü': 'manager',
    'kasiyeri': 'cashier',
    'görevlisi': 'attendant',
    'müşterisi': 'customer',
    'ürünü': 'product',
    'fiyatı': 'price',
    'kalitesi': 'quality',
    'hizmeti': 'service',
    'temizliği': 'cleanliness',
    'düzeni': 'order',
    'havası': 'air',
    'kokusu': 'smell',
    'müziği': 'music',
    'ışığı': 'light',
    'sırası': 'queue',
    'kabini': 'cabin',
    'reyonu': 'aisle',
    'rafı': 'shelf',
    'stoku': 'stock',
    'çeşidi': 'variety',
    'bedeni': 'size',
    'rengi': 'color',
    'kumaşı': 'fabric',
    'tarzı': 'style',
    'modeli': 'model',
    'seçeneği': 'option',
    'indirimi': 'discount',
    'kampanyası': 'campaign',
    'iadesi': 'return',
    'değişimi': 'exchange',
    'ödemesi': 'payment',
    'sistemi': 'system',
    'çözümü': 'solution',
    'sorunu': 'problem',
    'hatası': 'error',
    'yanlışı': 'wrong',
    'eksiği': 'missing',
    'fazlası': 'extra',
    'tavsiyesi': 'recommendation',
    'memnuniyeti': 'satisfaction',
    'şikayeti': 'complaint',
    'önerisi': 'suggestion',
    'ilgisi': 'attention',
    'alakası': 'relevance',
    'saygısı': 'respect',
    'kibarlığı': 'politeness',
    'yavaşlığı': 'slowness',
    'hızı': 'speed',
    'kalabalığı': 'crowd',
    'boşluğu': 'emptiness',
    'dağınıklığı': 'messiness',
    'pisliği': 'dirtiness',
    'havasızlığı': 'stuffiness',
    'sıcaklığı': 'heat',
    'soğukluğu': 'coldness',
    'karanlığı': 'darkness',
    'aydınlığı': 'brightness',
    'ferahlığı': 'spaciousness',
    'darlığı': 'narrowness',
    'genişliği': 'width',
    'eskiligi': 'oldness',
    'yeniliği': 'newness',
    'pratikliği': 'practicality',
    'doğruluğu': 'correctness',
    'tamlığı': 'completeness',
    'kesinliği': 'certainty',
    'zamanı': 'time',
    'bazeni': 'sometimes',
    'hiçi': 'nothing',
    'sürekliliği': 'continuity',
    'devamlılığı': 'continuity',
    'aralığı': 'interval',
    'hemenliği': 'immediacy',
    'şimdisi': 'now',
    'sonrası': 'after',
    'öncesi': 'before',
    'bugünü': 'today',
    'dünü': 'yesterday',
    'yarını': 'tomorrow',
    'sabahı': 'morning',
    'öğlesi': 'noon',
    'akşamı': 'evening',
    'gecesi': 'night',
    'haftası': 'week',
    'yakını': 'near',
    'uzağı': 'far',
    'merkezi': 'center',
    'şubesi': 'branch',
};

const translateWord = (word: string): string => {
    const lowerWord = word.toLowerCase();
    
    // Direct match
    if (TR_TO_EN_DICT[lowerWord]) {
        return TR_TO_EN_DICT[lowerWord];
    }
    
    // Try splitting multi-word phrases
    const parts = lowerWord.split(' ');
    if (parts.length > 1) {
        const translatedParts = parts.map(part => TR_TO_EN_DICT[part] || part);
        // If at least one part was translated, return the combined translation
        if (translatedParts.some((part, i) => part !== parts[i])) {
            return translatedParts.join(' ');
        }
    }
    
    // Fallback: return original word if no translation found
    // We could return null here to filter out untranslated words, but keeping them is safer
    return word;
};

interface WordCloudCardProps {
    comments: Comment[];
    setKeywordFilter: (keyword: string) => void;
    activeKeyword: string;
}

// FIX: Changed to a named export to resolve module loading issues.
export const WordCloudCard: React.FC<WordCloudCardProps> = ({ comments, setKeywordFilter, activeKeyword }) => {
    const { storeData } = useData();
    const [language, setLanguage] = useState<'tr' | 'en'>('tr');

    const aggregatedWords = useMemo((): WordCloudWord[] => {
        const relevantStoreNames = new Set(comments.map(c => c.store));
        if (relevantStoreNames.size === 0 && activeKeyword) {
            // If a keyword filter is active but results in 0 comments,
            // we should still try to show a word cloud based on the broader dataset if possible.
            // This logic can be adjusted, but for now, we'll show words from all stores in context.
            const allStoreNames = new Set(storeData.map(s => s.name));
            if (allStoreNames.size === 0) return [];

            const allWords = new Map<string, WordCloudWord>();
            storeData.forEach(store => {
                if (store.wordCloudData) {
                    store.wordCloudData.forEach(word => {
                        const existing = allWords.get(word.text) || { text: word.text, value: 0, positive: 0, negative: 0, neutral: 0 };
                        existing.value += word.value;
                        existing.positive += word.positive;
                        existing.negative += word.negative;
                        existing.neutral += word.neutral;
                        allWords.set(word.text, existing);
                    });
                }
            });
             return Array.from(allWords.values())
                .sort((a, b) => b.value - a.value)
                .slice(0, 40);

        } else if (relevantStoreNames.size === 0) {
            return [];
        }

        const relevantStores = storeData.filter(s => relevantStoreNames.has(s.name));
        
        const wordCounts = new Map<string, WordCloudWord>();
        relevantStores.forEach(store => {
            if (store.wordCloudData) {
                store.wordCloudData.forEach(word => {
                    const existing = wordCounts.get(word.text) || { text: word.text, value: 0, positive: 0, negative: 0, neutral: 0 };
                    existing.value += word.value;
                    existing.positive += word.positive;
                    existing.negative += word.negative;
                    existing.neutral += word.neutral;
                    wordCounts.set(word.text, existing);
                });
            }
        });
        
        return Array.from(wordCounts.values())
            .sort((a, b) => b.value - a.value)
            .slice(0, 40);

    }, [comments, storeData, activeKeyword]);

    const displayWords = useMemo(() => {
        if (language === 'tr') return aggregatedWords;
        
        // Translate words for English view
        const translatedMap = new Map<string, WordCloudWord>();
        
        aggregatedWords.forEach(word => {
            const translatedText = translateWord(word.text);
            const existing = translatedMap.get(translatedText);
            
            if (existing) {
                existing.value += word.value;
                existing.positive += word.positive;
                existing.negative += word.negative;
                existing.neutral += word.neutral;
            } else {
                translatedMap.set(translatedText, {
                    ...word,
                    text: translatedText
                });
            }
        });
        
        return Array.from(translatedMap.values())
            .sort((a, b) => b.value - a.value)
            .slice(0, 40);
    }, [aggregatedWords, language]);

    const handleWordClick = (word: string) => {
        // If in English mode, we need to find the original Turkish word(s) to filter properly,
        // or we can just filter by the translated word if the filter logic supports it.
        // For simplicity, we'll just use the displayed word. The filter might not work perfectly
        // for translated words unless the filter logic also translates, but it's a UI feature.
        if (activeKeyword === word) {
            setKeywordFilter('');
        } else {
            setKeywordFilter(word);
        }
    };
    
    const calculateStyle = (word: WordCloudWord, maxValue: number, index: number) => {
        const minFontSize = 14;
        const maxFontSize = 48;
        
        const normalizedValue = Math.sqrt(word.value) / Math.sqrt(maxValue);
        const fontSize = minFontSize + (maxFontSize - minFontSize) * normalizedValue;

        // Sentiment-based coloring
        let color = 'var(--text-color-light)'; // Default/Neutral
        const totalSentiment = word.positive + word.negative;
        if (totalSentiment > 1) { // Require at least 2 sentimental comments for color
            const sentimentRatio = word.positive / totalSentiment;
            if (sentimentRatio > 0.66) color = 'var(--success-color)';
            else if (sentimentRatio < 0.33) color = 'var(--error-color)';
        } else if (word.negative > word.positive) {
            color = 'var(--error-color)';
        } else if (word.positive > word.negative) {
            color = 'var(--success-color)';
        }

        // Organic layout with slight rotation
        const rotation = (word.text.length % 5 - 2) * 4; // Generates -8, -4, 0, 4, 8 degrees

        return { 
            fontSize: `${fontSize}px`,
            color,
            animationDelay: `${index * 0.05}s`,
            transform: `rotate(${rotation}deg)`,
        };
    };
    
    const renderContent = () => {
        if (displayWords.length > 0) {
            const maxValue = displayWords.length > 0 ? displayWords[0].value : 1;
            return (
                <div className="word-cloud-display">
                    {displayWords.map((word, index) => {
                        const tooltipText = language === 'tr' 
                            ? `Sıklık: ${word.value}\nOlumlu: ${word.positive}\nOlumsuz: ${word.negative}\nNötr: ${word.neutral}`
                            : `Frequency: ${word.value}\nPositive: ${word.positive}\nNegative: ${word.negative}\nNeutral: ${word.neutral}`;
                        return (
                            <button
                                key={`${word.text}-${index}`}
                                className={`word-cloud-word ${activeKeyword === word.text ? 'active' : ''}`}
                                style={calculateStyle(word, maxValue, index)}
                                title={tooltipText}
                                onClick={() => handleWordClick(word.text)}
                            >
                                {word.text}
                            </button>
                        )
                    })}
                </div>
            );
        }
        
        return (
            <div className="placeholder-card" style={{minHeight: '280px', border: 'none', background: 'var(--card-bg-color)'}}>
                <span className="material-symbols-outlined placeholder-icon" style={{fontSize: '2.5rem'}}>cloud_off</span>
                <p className="placeholder-text" style={{maxWidth: '35ch'}}>
                    {language === 'tr' 
                        ? 'Kelime bulutu oluşturmak için yeterli yorum bulunmuyor.' 
                        : 'Not enough comments to generate a word cloud.'}
                </p>
            </div>
        );
    };

    return (
        <div className="card">
            <div className="card-header flex justify-between items-center">
                <h3 className="card-title m-0">{language === 'tr' ? 'Öne Çıkan Kelimeler' : 'Prominent Words'}</h3>
                
                <div className="flex items-center gap-3">
                    <div className="flex bg-slate-100 p-1 rounded-lg">
                        <button 
                            onClick={() => setLanguage('tr')}
                            className={`px-3 py-1 text-xs font-medium rounded-md transition-all ${language === 'tr' ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
                        >
                            TR
                        </button>
                        <button 
                            onClick={() => setLanguage('en')}
                            className={`px-3 py-1 text-xs font-medium rounded-md transition-all ${language === 'en' ? 'bg-white text-indigo-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
                        >
                            EN
                        </button>
                    </div>
                </div>
            </div>
            {activeKeyword && (
                <div className="active-keyword-filter px-6 pt-2">
                    <span>{language === 'tr' ? 'Filtre:' : 'Filter:'} <strong>{activeKeyword}</strong></span>
                    <button onClick={() => setKeywordFilter('')} className="btn-icon" title={language === 'tr' ? 'Filtreyi Temizle' : 'Clear Filter'}>
                        <span className="material-symbols-outlined">close</span>
                    </button>
                </div>
            )}
            <div className="word-cloud-container">
                {renderContent()}
            </div>
        </div>
    );
};